---
- hosts: DEV
  become: True
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3
          - python3-pip
          - virtualenv
          - python3-setuptools
          - docker-compose
        state: latest
        update_cache: true
    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: demo-jenkins
        image: "jintsuy/demo-jenkins:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8090
