---
- hosts: dev
  become: True
  tasks:
    - name: Install Python3
      raw: sudo apt -y update && apt install -y python3
      when: check_python.rc != 0
    - name: Install python3-pip
      raw: sudo apt install -y python3-pip
      state: present
    - name: Install docker
      raw: sudo apt install -y docker-compose
      state: present
    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip3:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: demo-jenkins
        image: "jintsuy/demo-jenkins:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8090
