apiVersion: v1
kind: Deployment
metadata:
  name: demo-jenkins
  labels:
    app: demo-jenkins
spec:
  replicas: 3
  spec:
    containers:
      - name: demo-jenkins
        image: jintsuy/demo-jenkins:tagVersion
        ports:
          - name: web
            containerPort: 8080
        env:
        - name: NGX_VERSION
          value: 1.16.1