apiVersion: v1
kind: Pod
metadata:
  name: demo-jenkins
  labels:
    app: demo-jenkins
spec:
  containers:
    - name: demo-jenkins
      image: jintsuy/demo-jenkins:tagVersion
      ports:
        - containerPort: 8080