apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-jenkins-deployment
  labels:
    app: demo-jenkins
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: demo-jenkins
  template:
    metadata:
      labels:
        app: demo-jenkins
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: demo-jenkins
        image: jintsuy/demo-jenkins:tagVersion
        ports:
        - name: web
          containerPort:  8080
          protocol: TCP
        env:
        - name: NGX_VERSION
          value: 1.16.1
