name: CI-CD

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout da base de código
        uses: actions/checkout@v3.5.3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Construindo a imagem do worker
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            jintsuy/demo-jenkins:${{github.run_number}}
            jintsuy/demo-jenkins:latest
          build-args: |
            next_url=a6f33c0fbbb5347f1b7f1833bd9d1daa-157400115.us-east-1.elb.amazonaws.com
            next_url_api=a22bba60b4ca440b393dd90ce091c783-466327151.us-east-1.elb.amazonaws.com
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps: 
      - name: Checkout da base de código
        uses: actions/checkout@v3.5.3
      - name: Configurar as credenciais de acesso
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Configuração do Kubeconfig
        shell: bash
        run: |
          aws eks update-kubeconfig --name imersao-eks --region us-east-1
      - name: Deploy do worker no cluster Kubernetes 
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            home-broker/04-k8s-deploy/02-worker/deployment.yaml
          images: |
            fabricioveronez/trader-worker:${{github.run_number}}
            
      - name: Deploy da api no cluster Kubernetes
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            home-broker/04-k8s-deploy/03-api/deployment.yaml
          images: |
            fabricioveronez/trader-api:${{github.run_number}}

      - name: Deploy do frontend no cluster Kubernetes
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            home-broker/04-k8s-deploy/04-frontend/deployment.yaml
          images: |
            fabricioveronez/trader-web:${{github.run_number}}
